"""empty message

Revision ID: 945558cf8f03
Revises: aee9100e3db1
Create Date: 2022-08-06 20:31:35.289001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945558cf8f03'
down_revision = 'aee9100e3db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.String(length=300), nullable=True))
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###
